"""Field mapping dictionaries for KIS payloads."""

UNMAPPED_DESC = "미매핑(공식 스펙 확인 필요)"

ACCOUNT_FIELD_DESC = {
    "rt_cd": "응답 결과 코드",
    "msg_cd": "응답 메시지 코드",
    "msg1": "응답 메시지",
    "dnca_tot_amt": "예수금 총액",
    "nxdy_excc_amt": "익일 정산 예정 금액",
    "prvs_rcdl_excc_amt": "전일 미수/정산 관련 금액",
    "cma_evlu_amt": "CMA 평가금액",
    "bfdy_buy_amt": "전일 매수금액",
    "thdt_buy_amt": "당일 매수금액",
    "nxdy_auto_rdpt_amt": "익일 자동상환금액",
    "bfdy_sll_amt": "전일 매도금액",
    "thdt_sll_amt": "당일 매도금액",
    "d2_auto_rdpt_amt": "D+2 자동상환금액",
    "bfdy_tlex_amt": "전일 제세금",
    "thdt_tlex_amt": "당일 제세금",
    "tot_loan_amt": "총 대출금액",
    "scts_evlu_amt": "유가증권 평가금액",
    "tot_evlu_amt": "총 평가금액",
    "nass_amt": "순자산금액",
    "pchs_amt_smtl_amt": "총 매입금액",
    "evlu_amt_smtl_amt": "총 평가금액 합계",
    "evlu_pfls_smtl_amt": "평가손익 합계",
    "tot_stln_slng_chgs": "총 대주매각대금",
    "bfdy_tot_asst_evlu_amt": "전일 총자산평가금액",
    "asst_icdc_amt": "자산 증감액",
    "asst_icdc_erng_rt": "자산 증감 수익률(%)",
    "pdno": "종목코드",
    "prdt_name": "종목명",
    "hldg_qty": "보유수량",
    "ord_psbl_qty": "주문가능수량",
    "pchs_avg_pric": "평균매입단가",
    "pchs_amt": "매입금액",
    "prpr": "현재가",
    "evlu_amt": "평가금액",
    "evlu_pfls_amt": "평가손익금액",
    "evlu_pfls_rt": "평가손익률(%)",
    "fltt_rt": "등락률(%)",
    "trad_dvsn_name": "매매구분명",
    "bfdy_buy_qty": "전일매수수량",
    "bfdy_sll_qty": "전일매도수량",
    "thdt_buyqty": "당일매수수량",
    "thdt_sll_qty": "당일매도수량",
    "loan_dt": "대출일자",
    "expd_dt": "만기일자",
    "frcr_dncl_amt_2": "외화예수금",
    "ovrs_rlzt_pfls": "해외 실현손익",
    "ovrs_tot_pfls": "해외 총손익",
    "ovrs_tot_pchs_amt": "해외 총매입금액",
    "ovrs_tot_evlu_amt": "해외 총평가금액",
    "frst_bltn_exrt": "기준환율",
}

PRICE_FIELD_DESC = {
    "rt_cd": "응답 결과 코드",
    "msg_cd": "응답 메시지 코드",
    "msg1": "응답 메시지",
    "stck_shrn_iscd": "종목코드",
    "hts_kor_isnm": "종목명(한글)",
    "stck_prpr": "현재가",
    "prdy_vrss": "전일 대비",
    "prdy_vrss_sign": "전일 대비 부호",
    "prdy_ctrt": "전일 대비율(%)",
    "stck_oprc": "시가",
    "stck_hgpr": "고가",
    "stck_lwpr": "저가",
    "acml_vol": "누적 거래량",
    "acml_tr_pbmn": "누적 거래대금",
    "hts_avls": "시가총액",
    "frgn_hldn_qty": "외국인 보유수량",
    "frgn_ntby_qty": "외국인 순매수수량",
    "eps": "주당순이익(EPS)",
    "bps": "주당순자산(BPS)",
    "stck_mxpr": "상한가",
    "stck_llam": "하한가",
    "wghn_avrg_stck_prc": "가중평균주가",
    "vol_tnrt": "거래량회전율",
    "short_over_yn": "단기과열 여부",
    "mrkt_warn_cls_code": "시장경고 구분코드",
    "new_hgpr_lwpr_cls_code": "신고가/신저가 구분코드",
}

OVERSEAS_PRICE_FIELD_DESC = {
    "symb": "해외 종목코드",
    "rsym": "Reuters 종목코드",
    "zdiv": "거래소 구분",
    "basr_tlcl": "기준시간(현지)",
    "last": "현재가",
    "open": "시가",
    "high": "고가",
    "low": "저가",
    "clos": "전일종가",
    "tvol": "거래량",
    "tamt": "거래대금",
    "diff": "전일대비",
    "rate": "등락률(%)",
    "e_hogau": "매도호가",
    "e_hogab": "매수호가",
    "tomv": "시가총액",
    "t_xsgn": "대비 부호",
    "e_ordyn": "해외 주문 가능 여부",
    "vnit": "거래통화",
    "pbid": "전일 종가 대비 기준값",
    "avol": "평균 거래량",
    "e_hoga": "해외호가 기준값",
    "bidp": "매수호가",
    "askp": "매도호가",
    "xymd": "현지 영업일자",
    "xhms": "현지 시각",
    "kymd": "한국 기준일자",
    "khms": "한국 기준시각",
}

ORDER_FIELD_DESC = {
    "krx_fwdg_ord_orgno": "한국거래소전송주문조직번호",
    "odno": "주문번호",
    "ord_tmd": "주문시각",
    "ord_qty": "주문수량",
    "ord_unpr": "주문단가",
    "ovrs_ord_unpr": "해외주문단가",
    "rvse_cncl_dvsn_cd": "정정취소구분코드",
    "ord_dvsn": "주문구분",
    "ord_dvsn_cd": "주문구분코드",
    "sll_buy_dvsn_cd": "매도매수구분코드",
    "pdno": "종목코드",
    "ovrs_excg_cd": "해외거래소코드",
    "ctac_tlno": "연락전화번호",
    "ord_svr_dvsn_cd": "주문서버구분코드",
    "ord_dt": "주문일자",
    "rjct_rson": "거부사유",
    "rjct_rson_name": "거부사유명",
    "ord_stat": "주문상태",
    "ord_tmd": "주문시각",
    "tot_ccld_qty": "총 체결수량",
    "tot_ccld_amt": "총 체결금액",
    "rmn_qty": "미체결수량",
    "ft_ord_qty": "정정 후 주문수량",
    "ft_ord_unpr": "정정 후 주문단가",
    "nccs_qty": "미체결수량",
    "ccld_qty": "체결수량",
    "ccld_unpr": "체결단가",
    "ovrs_ccld_unpr": "해외 체결단가",
    "ovrs_ccld_qty": "해외 체결수량",
    "ovrs_ccld_amt": "해외 체결금액",
}
