"""Capability/scope/filter catalog definitions."""

KIS_API_SCOPE_CATALOG = [
    {
        "market_scope": "domestic",
        "domain": "account",
        "feature": "계좌 잔고/보유종목 조회",
        "status": "implemented",
        "api": "/api/v1/kis/balance",
        "note": "실전/모의 계좌 모두 지원",
    },
    {
        "market_scope": "domestic",
        "domain": "stock",
        "feature": "현재가 조회",
        "status": "implemented",
        "api": "/api/v1/kis/price/{symbol}",
    },
    {
        "market_scope": "domestic",
        "domain": "stock",
        "feature": "호가 조회",
        "status": "implemented",
        "api": "/api/v1/kis/orderbook/{symbol}",
    },
    {
        "market_scope": "domestic",
        "domain": "stock",
        "feature": "차트(일/주/월)",
        "status": "implemented",
        "api": "/api/v1/kis/chart/daily/{symbol}",
    },
    {
        "market_scope": "domestic",
        "domain": "trade",
        "feature": "현금 매수/매도",
        "status": "implemented",
        "api": "/api/v1/kis/order/cash",
    },
    {
        "market_scope": "domestic",
        "domain": "trade",
        "feature": "정정/취소",
        "status": "implemented",
        "api": "/api/v1/kis/order/rvsecncl",
    },
    {
        "market_scope": "domestic",
        "domain": "trade",
        "feature": "예약 매수/매도",
        "status": "implemented",
        "api": "/api/v1/kis/order/reserve",
    },
    {
        "market_scope": "overseas",
        "domain": "stock",
        "feature": "현재가 조회",
        "status": "implemented",
        "api": "/api/v1/kis/overseas/price/{exchange}/{symbol}",
    },
    {
        "market_scope": "overseas",
        "domain": "stock",
        "feature": "차트(일/주/월)",
        "status": "implemented",
        "api": "/api/v1/kis/overseas/chart/daily/{exchange}/{symbol}",
    },
    {
        "market_scope": "overseas",
        "domain": "trade",
        "feature": "현금 매수/매도",
        "status": "implemented",
        "api": "/api/v1/kis/overseas/order/cash",
    },
    {
        "market_scope": "overseas",
        "domain": "trade",
        "feature": "정정/취소",
        "status": "implemented",
        "api": "/api/v1/kis/overseas/order/rvsecncl",
    },
    {
        "market_scope": "overseas",
        "domain": "trade",
        "feature": "예약주문",
        "status": "not_supported",
        "api": "해외주식 예약주문",
        "note": "MVP 범위 제외",
    },
]

STOCK_FILTER_CATALOG = [
    {
        "market_scope": "domestic",
        "status": "implemented",
        "method": "GET",
        "testable": True,
        "api": "/api/v1/kis/meta/stocks/search",
        "purpose": "종목 키워드 검색",
        "filters": [
            {"name": "keyword", "required": True, "type": "string", "description_ko": "종목명/종목코드 포함 검색어"},
            {"name": "limit", "required": False, "type": "int", "description_ko": "최대 결과 개수 (1~200)", "default": 30},
        ],
    },
    {
        "market_scope": "domestic",
        "status": "implemented",
        "method": "GET",
        "testable": True,
        "api": "/api/v1/kis/meta/stock-fields/{symbol}",
        "purpose": "현재가/호가 필드 전수 조회",
        "filters": [
            {"name": "symbol", "required": True, "type": "string", "description_ko": "종목코드 (예: 005930)"},
        ],
    },
    {
        "market_scope": "domestic",
        "status": "implemented",
        "method": "GET",
        "testable": True,
        "api": "/api/v1/kis/chart/daily/{symbol}",
        "purpose": "일/주/월 차트 조회",
        "filters": [
            {"name": "symbol", "required": True, "type": "string", "description_ko": "종목코드"},
            {"name": "period_code", "required": False, "type": "enum", "description_ko": "조회 주기", "options": ["D", "W", "M"], "default": "D"},
            {"name": "adjusted_price", "required": False, "type": "enum", "description_ko": "수정주가 반영 여부", "options": ["0", "1"], "default": "1"},
        ],
    },
    {
        "market_scope": "overseas",
        "status": "implemented",
        "method": "GET",
        "testable": True,
        "api": "/api/v1/kis/overseas/price/{exchange}/{symbol}",
        "purpose": "해외주식 현재가 조회",
        "filters": [
            {"name": "exchange", "required": True, "type": "enum", "description_ko": "거래소 코드", "options": ["NASD", "NYSE", "AMEX", "SEHK", "TKSE"]},
            {"name": "symbol", "required": True, "type": "string", "description_ko": "해외 티커 (예: AAPL)"},
        ],
    },
    {
        "market_scope": "overseas",
        "status": "implemented",
        "method": "GET",
        "testable": True,
        "api": "/api/v1/kis/overseas/chart/daily/{exchange}/{symbol}",
        "purpose": "해외주식 일/주/월 차트 조회",
        "filters": [
            {"name": "exchange", "required": True, "type": "enum", "description_ko": "거래소 코드", "options": ["NASD", "NYSE", "AMEX", "SEHK", "TKSE"]},
            {"name": "symbol", "required": True, "type": "string", "description_ko": "해외 티커"},
            {"name": "period_code", "required": False, "type": "enum", "description_ko": "조회 주기", "options": ["D", "W", "M"], "default": "D"},
            {"name": "adjusted_price", "required": False, "type": "enum", "description_ko": "수정주가 반영 여부", "options": ["0", "1"], "default": "1"},
        ],
    },
]
