"""KIS API inventory and coverage matrix definitions for smoke testing."""

from __future__ import annotations

from typing import Any, Dict, List

DEFAULT_DOMESTIC_SYMBOL = "005930"
DEFAULT_OVERSEAS_EXCHANGE = "NASD"
DEFAULT_OVERSEAS_SYMBOL = "AAPL"


def get_api_inventory() -> List[Dict[str, Any]]:
    """Return canonical API inventory entries across domestic/overseas scopes."""
    return [
        {
            "id": "domestic.quote.price",
            "market": "domestic",
            "domain": "quote",
            "method": "GET",
            "endpoint": "/api/v1/kis/price/{symbol}",
            "path_params": {"symbol": DEFAULT_DOMESTIC_SYMBOL},
            "risk_level": "safe",
            "description": "국내 현재가 조회",
        },
        {
            "id": "domestic.quote.orderbook",
            "market": "domestic",
            "domain": "quote",
            "method": "GET",
            "endpoint": "/api/v1/kis/orderbook/{symbol}",
            "path_params": {"symbol": DEFAULT_DOMESTIC_SYMBOL},
            "risk_level": "safe",
            "description": "국내 호가 조회",
        },
        {
            "id": "domestic.account.balance",
            "market": "domestic",
            "domain": "account",
            "method": "GET",
            "endpoint": "/api/v1/kis/balance",
            "risk_level": "safe",
            "description": "국내 계좌 잔고 조회",
        },
        {
            "id": "domestic.chart.daily",
            "market": "domestic",
            "domain": "chart",
            "method": "GET",
            "endpoint": "/api/v1/kis/chart/daily/{symbol}",
            "path_params": {"symbol": DEFAULT_DOMESTIC_SYMBOL},
            "query_params": {"period_code": "D", "adjusted_price": "1"},
            "risk_level": "safe",
            "description": "국내 일봉/주봉/월봉 조회",
        },
        {
            "id": "domestic.search.keyword",
            "market": "domestic",
            "domain": "search",
            "method": "GET",
            "endpoint": "/api/v1/kis/meta/stocks/search",
            "query_params": {"keyword": "삼성", "limit": 10},
            "risk_level": "safe",
            "description": "국내 종목 키워드 검색",
        },
        {
            "id": "domestic.quote.investor_profile",
            "market": "domestic",
            "domain": "quote",
            "method": "GET",
            "endpoint": "/api/v1/kis/strategy/investor-buy-leaders",
            "query_params": {
                "subject": "foreign",
                "market": "KOSPI",
                "sort_by": "net_buy_amount",
                "order": "desc",
                "limit": 5,
                "max_candidates": 10,
            },
            "risk_level": "safe",
            "description": "주체별 매수주도 종목 랭킹(원천 투자자+현재가 결합)",
        },
        {
            "id": "domestic.filter.catalog",
            "market": "domestic",
            "domain": "filter",
            "method": "GET",
            "endpoint": "/api/v1/kis/meta/stock-filters",
            "risk_level": "safe",
            "description": "필터 카탈로그 조회",
        },
        {
            "id": "strategy.schema",
            "market": "domestic",
            "domain": "strategy",
            "method": "GET",
            "endpoint": "/api/v1/kis/strategy/schema",
            "risk_level": "safe",
            "description": "전략 파라미터 스키마 조회",
        },
        {
            "id": "strategy.mapping",
            "market": "domestic",
            "domain": "strategy",
            "method": "POST",
            "endpoint": "/api/v1/kis/strategy/mapping",
            "body": {"market": "domestic", "limit": 5, "price_min": 10000, "volume_min": 100000},
            "risk_level": "safe",
            "description": "전략 필터-API 매핑 조회",
        },
        {
            "id": "strategy.search_filter.domestic",
            "market": "domestic",
            "domain": "strategy",
            "method": "POST",
            "endpoint": "/api/v1/kis/strategy/search-filter",
            "body": {
                "keyword": "삼성",
                "market": "domestic",
                "strategy": {
                    "market": "domestic",
                    "limit": 5,
                    "price_min": 10000,
                    "price_max": 2000000,
                    "volume_min": 10000,
                },
                "max_candidates": 10,
            },
            "risk_level": "safe",
            "description": "국내 키워드+필터 검색 파이프라인",
        },
        {
            "id": "domestic.filter.fields",
            "market": "domestic",
            "domain": "filter",
            "method": "GET",
            "endpoint": "/api/v1/kis/meta/stock-fields/{symbol}",
            "path_params": {"symbol": DEFAULT_DOMESTIC_SYMBOL},
            "risk_level": "safe",
            "description": "국내 필드 매핑 조회",
        },
        {
            "id": "domestic.order.cash.schema",
            "market": "domestic",
            "domain": "order",
            "method": "POST",
            "endpoint": "/api/v1/kis/order/cash",
            "body": {"side": "buy", "symbol": DEFAULT_DOMESTIC_SYMBOL, "qty": 0, "price": "70000"},
            "expected_status": [422],
            "risk_level": "schema_only",
            "description": "국내 현금주문 요청 스키마 검증",
        },
        {
            "id": "domestic.order.revise_cancel.schema",
            "market": "domestic",
            "domain": "revise_cancel",
            "method": "POST",
            "endpoint": "/api/v1/kis/order/rvsecncl",
            "body": {"mode": "cancel", "orgn_odno": "", "qty": 0, "order_price": "0"},
            "expected_status": [422],
            "risk_level": "schema_only",
            "description": "국내 정정/취소 요청 스키마 검증",
        },
        {
            "id": "domestic.order.reserve.schema",
            "market": "domestic",
            "domain": "order",
            "method": "POST",
            "endpoint": "/api/v1/kis/order/reserve",
            "body": {"side": "buy", "symbol": DEFAULT_DOMESTIC_SYMBOL, "qty": 0, "price": "70000"},
            "expected_status": [422],
            "risk_level": "schema_only",
            "description": "국내 예약주문 요청 스키마 검증",
        },
        {
            "id": "overseas.quote.price",
            "market": "overseas",
            "domain": "quote",
            "method": "GET",
            "endpoint": "/api/v1/kis/overseas/price/{exchange}/{symbol}",
            "path_params": {"exchange": DEFAULT_OVERSEAS_EXCHANGE, "symbol": DEFAULT_OVERSEAS_SYMBOL},
            "risk_level": "safe",
            "description": "해외 현재가 조회",
        },
        {
            "id": "overseas.chart.daily",
            "market": "overseas",
            "domain": "chart",
            "method": "GET",
            "endpoint": "/api/v1/kis/overseas/chart/daily/{exchange}/{symbol}",
            "path_params": {"exchange": DEFAULT_OVERSEAS_EXCHANGE, "symbol": DEFAULT_OVERSEAS_SYMBOL},
            "query_params": {"period_code": "D", "adjusted_price": "1"},
            "risk_level": "safe",
            "description": "해외 차트 조회",
        },
        {
            "id": "overseas.search.keyword",
            "market": "overseas",
            "domain": "search",
            "method": "POST",
            "endpoint": "/api/v1/kis/strategy/search-filter",
            "body": {
                "keyword": "AAPL",
                "market": "overseas",
                "strategy": {
                    "market": "overseas",
                    "limit": 5,
                    "price_min": 1,
                    "price_max": 10000,
                },
            },
            "risk_level": "safe",
            "description": "해외 키워드+필터 검색 파이프라인",
        },
        {
            "id": "strategy.search_filter.overseas",
            "market": "overseas",
            "domain": "strategy",
            "method": "POST",
            "endpoint": "/api/v1/kis/strategy/search-filter",
            "body": {
                "keyword": "MSFT",
                "market": "overseas",
                "strategy": {
                    "market": "overseas",
                    "limit": 5,
                    "price_min": 10,
                    "price_max": 10000,
                },
                "max_candidates": 8,
            },
            "risk_level": "safe",
            "description": "해외 키워드+필터 검색 파이프라인(전략 도메인)",
        },
        {
            "id": "overseas.order.cash.schema",
            "market": "overseas",
            "domain": "order",
            "method": "POST",
            "endpoint": "/api/v1/kis/overseas/order/cash",
            "body": {
                "side": "buy",
                "exchange": DEFAULT_OVERSEAS_EXCHANGE,
                "symbol": DEFAULT_OVERSEAS_SYMBOL,
                "qty": 0,
                "price": "150",
            },
            "expected_status": [422],
            "risk_level": "schema_only",
            "description": "해외 주문 요청 스키마 검증",
        },
        {
            "id": "overseas.order.revise_cancel.schema",
            "market": "overseas",
            "domain": "revise_cancel",
            "method": "POST",
            "endpoint": "/api/v1/kis/overseas/order/rvsecncl",
            "body": {
                "mode": "cancel",
                "exchange": DEFAULT_OVERSEAS_EXCHANGE,
                "symbol": DEFAULT_OVERSEAS_SYMBOL,
                "orgn_odno": "",
                "qty": 0,
                "order_price": "0",
            },
            "expected_status": [422],
            "risk_level": "schema_only",
            "description": "해외 정정/취소 요청 스키마 검증",
        },
        {
            "id": "autotrade.guard",
            "market": "domestic",
            "domain": "autotrade",
            "method": "GET",
            "endpoint": "/api/v1/kis/autotrade/guard",
            "risk_level": "safe",
            "description": "자동거래 가드 조회",
        },
        {
            "id": "autotrade.execute.schema",
            "market": "domestic",
            "domain": "autotrade",
            "method": "POST",
            "endpoint": "/api/v1/kis/autotrade/execute",
            "body": {"mode": "dry_run", "market": "domestic", "symbol": "005930", "side": "buy", "qty": 0, "price": "70000"},
            "expected_status": [422],
            "risk_level": "schema_only",
            "description": "자동거래 실행 요청 스키마 검증",
        },
        {
            "id": "autotrade.scenario_test",
            "market": "domestic",
            "domain": "autotrade",
            "method": "POST",
            "endpoint": "/api/v1/kis/autotrade/scenario-test",
            "risk_level": "safe",
            "description": "자동거래 시나리오 테스트 실행",
        },
    ]


def build_coverage_matrix(items: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Build matrix counts by market/domain for UI and reports."""
    matrix: Dict[str, Dict[str, int]] = {}
    for item in items:
        market = str(item.get("market", "unknown"))
        domain = str(item.get("domain", "unknown"))
        matrix.setdefault(market, {})
        matrix[market][domain] = matrix[market].get(domain, 0) + 1
    return {"total": len(items), "matrix": matrix}
